---
- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: true
    
- name: Disable systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Remove symlink
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Create resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 127.0.0.1

- name: Configure dnsmasq
  ansible.builtin.copy:
    dest: /etc/dnsmasq.d/10-consul
    content: |
      server=/consul/127.0.0.1#8600

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
    enabled: true
